### ISSUE TITLE
Selecting "disable extension on search results page" also disables extension in subscription tab

### ISSUE THREAD

**Issue by da-batt** [domdomegg/hideytthumbnails-extension#17]

**Comment by da-batt** [comment]
Upon further testing I discovered that the page needs to be refreshed in order for the extension to toggle on and off.

Example:
Start in subscription tab - thumbnails are blurred
Search for a video - thumbnails are blurred (expected result: thumbnails show normally)
Refresh - thumbnails show normally
Go back to subscription tab - thumbnails show normally (expected result: thumbnails are blurred)

**Comment by domdomegg** [comment]
Thanks for the report! I have been able to reprorduce this. I suspect this is happening because when navigating within YouTube sometimes it uses client-side navigation, causing the extension not to re-evaluate what's going on.

I suspect we just need to add a window path change listener to inject.js that calls `updateElem` (similar to how we have one for `browser.storage.onChanged`).

I'll try to implement this later today.
